/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'fabio.oliveira' at '21.09.16 22:09' with Gradle 2.1
 *
 * @author fabio.oliveira, @date 21.09.16 22:09
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
