/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'fabio.oliveira' at '21.09.16 11:05' with Gradle 2.1
 *
 * @author fabio.oliveira, @date 21.09.16 11:05
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
